title: UserLogin
theme: jekyll-theme-cayman
defaults:
  - scope:
      path: ''
    values:
      title: UserLogin
      google_analytics: 'G-JTZ6QQSV6X'
      download_url: 'https://www.spigotmc.org/resources/userlogin.80669/'
      support_url: 'https://discord.gg/gbjaEDzRXU'
